name: Analyze, build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment:
    name: "🚀 Deploy"
    if: github.ref == 'refs/heads/main'
    needs: [analyze]
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            npm ci
            npm run build
